services:
  auth:
    image: "auth:latest"
    environment:
      - MONGO_URI=mongodb://root:root@mongo:27017/auth?authSource=admin
      - SECRET_KEY=micronest
    ports:
      - 8081:3000
    depends_on:
      - mongo
    networks:
      - app-network
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    volumes:
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js
    networks:
      - app-network

networks:
  app-network:
